### ISSUE TITLE
Colon in dn causes URISyntaxException leading to hardcoded "value"

### ISSUE THREAD

**Issue by JaspreetKaur16** [spring-projects/spring-ldap#540]
I am using spring-ldap v1.2.1 jar.
On using LDAP dn that contains colon, the following API in LdapRdnComponent class throws URISyntaxException leading to harded "value".

The problematic LDAP dn:
cn=Testing QPP:testqpp2, ou=Users, ou=XXX, dc=YYY, dc=ZZZ, dc=com

public String encodeUrl() {
		// Use the URI class to properly URL encode the value.
		try {
			URI valueUri = new URI(null, null, "Testing QPP:testqpp2", null);
			return key + "=" + valueUri.toString();
		}
		catch (URISyntaxException e) {
			// This should really never happen...
			return key + "=" + "value"; //BUT THE CODE COMES HERE..!!!!
		}
	}

Can you please suggest a solution for LDAP dn's that contain colon?

Thanks,
Jaspreet

**Comment by JaspreetKaur16** [comment]
Hello,
Has any one encountered this issue? any workaround ?

Thanks,
Jaspreet

**Comment by jzheaux** [comment]
Hi, @JaspreetKaur16, thanks for reaching out. 

Spring LDAP 1.x has not been supported for some time, so please do your best to [update to a supported version](https://spring.io/projects/spring-ldap#support). In that case, it's also recommended that you use `LdapName` instead of `DistinguishedName`.

The issue you are dealing with is that when you have a URI like "a:b", then "a" is the scheme. Schemes cannot have spaces in them, and so Java is appropriately complaining. If you need to call `encodeUrl`, please make sure that the value is a valid URL.

If you have additional questions, please post to [StackOverflow](https://stackoverflow.com), as this will allow the community to help take a closer look.
