### ISSUE TITLE
Support IgnoreSizeLimitExceededException in SingleContextSource class

### ISSUE THREAD

**Issue by maunzCache** [spring-projects/spring-ldap#544]
I have a case where i want to use paged results with spring-ldap. However, the whole thing is really complicated for me because you have to consider a lot of configuration regarding the client application accessing ldap and the ldap server (OpenLDAP in my case).

First and foremost a common issue and the reason why i want to use pagination is that a search request easily exceeds the size request limit of the server which is okay i guess. There is no practical way to get to know the size limit of the target ldap server (except for knowing it by hard) so lookup tend to be trial-and-error. It is not possible to edit the ldap configuration and i cannot filter the results any more. It is very likely that a lookup always exceeds a limit.

This is where pagination comes in handy. If a lookup exceeds a client-sided limit (!) then the request is paused and continued from the next page. In case the paginated lookup either exceeds the client or the server sided limit an SizeLimitExceededException is thrown by the java runtime (wrapped in a spring exception). A common way to work around this issue is to catch the exception and retry the lookup with a lower limit.

There is an example implementation in the [reference documentation](https://docs.spring.io/autorepo/docs/spring-ldap/2.3.2.RELEASE/reference/#paged-search-results) of spring-ldap using the SingleContextSource class. This is quite conventient but does not help that much because the issue i want to solve - use pagination because of large responses creating exceptions - is unsolveable as the SingleContextSource class does ignore any exception thrown by the LdapOperation.search() implementation.

It would be nice if the SingleContextSource implementation would support either passing the LdapTemplate class or the additional arguments to turn of exception ignoring. I know that this implementation is more like a proof-of-concept but it comes in really handy as i find it troublesome to work with ldap at all and feel not quite experienced in software development to find another way or implemented it myself.

**Comment by jzheaux** [comment]
If you are wanting to supply your own `LdapOperations`, which seems a reasonable way to address this, then there's not a whole lot that `doWithSingleContext` can do for you. This is because it's designed to construct an `LdapOperations` using the provided criteria and then invoke the provided callback with the constructed `LdapOperations`. In your case, you'd just construct the `SingleContextSource` and `LdapOperations` how you need them, and then run whatever code you want to.

To illustrate, I'll modify [the sample from the reference](https://docs.spring.io/spring-ldap/docs/2.3.2.RELEASE/reference/#paged-search-results) you linked to:

```java
SingleContextSource single = new SingleContextSource(contextSource.getReadOnlyContext());
LdapTemplate operations = new LdapTemplate(single);
operations.setIgnoreSizeLimitExceededException(false);
List<String> result = new LinkedList<String>();

do {
  List<String> oneResult = operations.search(
    "ou=People",
    "(&(objectclass=person))",
    searchControls,
    CN_ATTRIBUTES_MAPPER,
    processor);
  result.addAll(oneResult);
} while(processor.hasMore());
```

I'm going to close this as answered, but please feel free to comment further if I've misunderstood.

**Comment by maunzCache** [comment]
I really cannot remember that use case any more but i guess it was solved a long time ago already.
Thanks for answering such an old ticket. Appreciate it :)
