### ISSUE TITLE
Multiply Base query

### ISSUE THREAD

**Issue by laperez** [spring-projects/spring-ldap#565]
I have two base. Is it possible to run the query on two directory bases? For example I 
I have query().base(list name), this is possible to do in some way.

Greetings

**Comment by jzheaux** [comment]
Thanks for getting in touch! Generally, no. LDAP being hierarchical, it's better to try and go up one level in the hierarchy.

For more guidance, it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
