### ISSUE TITLE
In order to perform this operation a successful bind must be completed on the connection.

### ISSUE THREAD

**Issue by wangfan0524** [spring-projects/spring-ldap#629]
when i use ldaptemplate.search method ,it keeps prompting that the exception.But the username and password and the ldap client configuration are determined to be no problem，Have you encountered this problem? thank you

![image](https://user-images.githubusercontent.com/37073064/155663401-f216b11d-0bbc-4655-8cb4-3475d715eae4.png)

![image](https://user-images.githubusercontent.com/37073064/155663099-46d28a47-3d1d-4460-9a80-1d05b30bc778.png)

**Comment by jzheaux** [comment]
Thanks for getting in touch! It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.
