### ISSUE TITLE
java.lang.reflect.UndeclaredThrowableException with spring-ldap-core 2.3.2.RELEASE and above

### ISSUE THREAD

**Issue by aplatt** [spring-projects/spring-ldap#660]
I am using the following version of Java:

```
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~18.04-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
```

When I make the following lookup using StartTLS with spring-ldap-core 2.3.1.RELEASE for a non existent dn:

```
DefaultTlsDirContextAuthenticationStrategy tlsAuthStratagy = new DefaultTlsDirContextAuthenticationStrategy();
tlsAuthStratagy.setShutdownTlsGracefully(true);
contextSource.setAuthenticationStrategy(tlsAuthStratagy);
PoolingContextSource poolingContextSource = new PoolingContextSource();
poolingContextSource.setMaxActive(5);
poolingContextSource.setContextSource(contextSource);
proxy = new TransactionAwareContextSourceProxy(poolingContextSource);
LdapTemplate ldapTemplate = new LdapTemplate(proxy);
ldapTemplate.lookup(dn);
```

I receive the following exception as expected:

`org.springframework.ldap.NameNotFoundException`

However, from spring-ldap-core 2.3.2.RELEASE and above, I received the following exception:

`java.lang.reflect.UndeclaredThrowableException`

This only happens when I attempt to use StartTLS ie. call setAuthenticationStrategy().

**Comment by jzheaux** [comment]
Thanks for the report, @aplatt. The only commit I can see between those two releases that may be related is c0def8583fd888acbc154192083db47dfb42dc06.

I have not been able to reproduce this yet, though I imagine it has something to do with the above arrangement is propagating exceptions. Does the `UndeclaredThrowableException` have a caused by or anything else that indicates what its cause is? Or, are you able to produce a GitHub sample that demonstrates the error?

**Comment by prthakre** [comment]
@aplatt Were you able to resolve this? With 3.3.2 the `cause` seems to be `null`

**Comment by aplatt** [comment]
I stayed with 2.3.1.RELEASE which didn't have the problem.
