### ISSUE TITLE
LdapTemplate.create throws "LDAP: error code 32 - No Such Object"

### ISSUE THREAD

**Issue by Alexey-Makarevich** [spring-projects/spring-ldap#701]
Trying to create entry (person or group) with spring-ldap - create or save ( use of bind) always gives "LDAP: error code 32 - No Such Object"

Spring Boot 2.7.3, spring-ldap-core 2.4.1
Tested with JDK 1.8, 11, 17 and OpenLDAP\FreeIPA

See the following sample: https://github.com/Alexey-Makarevich/spring-ldap-bind-issue
The project uses Person and OdmPersonRepo classes from https://docs.spring.io/spring-ldap/docs/2.4.0/reference/#odm .
It shows that bind can not create person (item) in Ldap.
But if we use javax.naming.directory.DirContext.createSubcontext it successfully creates person.

**Comment by jzheaux** [comment]
Hi, @Alexey-Makarevich. there are a couple of issues with your test. 

The first is that you set the DN when preparing the `Person` for creation to include `dc=example,dc=org`. Since this is already set as the base for `DirContext` as well, the bind ends up asking to create `cn=testUsser,ou=somOu,dc=example,dc=org,dc=example,dc=org`. If you only set the DN to `cn=testUsser,ou=someOu`, then the test passes.

If you are able to remove the `ou=someOu` base from the `@Entry` definition, then you can go simpler than that and allow `LdapTemplate` to calculate the DN for you.

I've added a [pull request](https://github.com/Alexey-Makarevich/spring-ldap-bind-issue/pull/1) to your repo to describe the changes.

At this point, it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). Since we prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), if you have more questions, please feel free to update this issue with a link to the re-posted question (so that I and other people can find it) or add more detail if you feel this is a genuine bug.
