### ISSUE TITLE
Incorrect documentation links

### ISSUE THREAD

**Issue by breun** [spring-projects/spring-ldap#884]
On https://spring.io/projects/spring-ldap#learn there are some incorrect links:

* 3.2.4-SNAPSHOT links to https://docs.spring.io/spring-ldap/reference/3.2-SNAPSHOT/index.html, which shows the documentation for 3.2.5-SNAPSHOT.
* 3.2.3-SNAPSHOT links to https://docs.spring.io/spring-ldap/reference/3.2, which shows the documentation for 3.2.4.
* 3.2.3 links to https://docs.spring.io/spring-ldap/reference/3.2.3/index.html, which redirects to https://docs.spring.io/spring-ldap/reference/index.html, which shows the documentation for 3.2.4.
* 3.2.2 links to https://docs.spring.io/spring-ldap/reference/3.2, which shows the documentation for 3.2.4.
* 3.1.6-SNAPSHOT links to https://docs.spring.io/spring-ldap/reference/3.1-SNAPSHOT/index.html, which shows the documentation for 3.1.7-SNAPSHOT.
* 3.1.5-SNAPSHOT links to https://docs.spring.io/spring-ldap/reference/3.1.5-SNAPSHOT/index.html, which redirects to https://docs.spring.io/spring-ldap/reference/3.1-SNAPSHOT/index.html, which shows the documentation for 3.1.7-SNAPSHOT.
* 3.1.5 links to https://docs.spring.io/spring-ldap/reference/3.1.5/index.html, which redirects to https://docs.spring.io/spring-ldap/reference/3.1/index.html, which displays the documentation for 3.1.6.

**Comment by jzheaux** [comment]
Thanks, @breun. It appears the automation is not correctly removing previous release versions from that page. I'll leave this ticket open to investigate that.

**Comment by jzheaux** [comment]
The automation appears to fail when [scanning for the previous version](https://github.com/spring-projects/spring-ldap/actions/runs/10404469225/job/28813300201#step:8:30). Since one of them is not in a format the automation recognizes, the delete step failed.

That version, `2.3.8.RELEASE` is no longer supported, so I've deleted the link. I've created https://github.com/spring-io/spring-security-release-tools/issues/51 to take a closer look at that.
